export const DUMMY_COURSES = [
  {
    id: "1XU7bkRI0kvbB1AqRPNR",
    maxSeats: 30,
    createdAt: "2025-03-02T08:42:44.687Z",
    price: "123",
    isAds: false,
    href: "",
    lessons: "7",
    featuredImage:
      "https://content.kaspersky-labs.com/se/com/content/en-global/images/repository/isc/2017-images/What-is-Cyber-Security/What-is-Cyber-Security.jpg",
    title: "Cyber Security Lucas",
    galleryImgs: [
      "https://eu-images.contentstack.com/v3/assets/blt69509c9116440be8/blt8ffb90a2f64bacfa/6776f4544b281ca5e2bc465a/cybersecurity_NicoElNino-AlamyStockPhoto.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUtCynmF_iUbXJlz5gDHgZ9P001Loq8Uf7zg&s",
      "https://imgproxy.divecdn.com/Sw487ygwxSdQb27s_HixyyiopicX-waj-bJt5H5TIqQ/g:ce/rs:fill:1200:675:1/Z3M6Ly9kaXZlc2l0ZS1zdG9yYWdlL2RpdmVpbWFnZS9HZXR0eUltYWdlcy0xNDIwMDM5OTAwLmpwZw==.webp",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    tags: [],
    lecturerId: "pPokxCtkWkR2x35Yh5GF72cDb2m2",
    category: "IT",
    description: "Lucas is master of cybersecurity",
    duration: "7",
    currentEnrollments: 30,
    level: "Beginner",
    modifiedAt: "2025-03-02T08:42:44.687Z",
  },
  {
    id: "20lGYpMjNVDo2PiVr4aD",
    featuredImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdeo1uoyb6oQS7eePlZNsnk0W_4aB-AbcQ9A&s",
    description: "Deep dive into Java for experienced programmers.",
    href: "/courses/java-advanced",
    lecturerId: "pPokxCtkWkR2x35Yh5GF72cDb2m2",
    category: "Programming",
    lessons: 50,
    createdAt: "2024-10-01",
    title: "Advanced Java Programming",
    galleryImgs: [
      "https://localo.com/assets/img/definitions/what-is-java.webp",
      "https://www.jrebel.com/sites/default/files/styles/social_preview_image/public/image/2020-05/image-blog-revel-top-java-tools.jpg?itok=34P5v4AD",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    tags: ["Java", "Advanced"],
    maxSeats: 20,
    duration: "10 weeks",
    price: 69.99,
    currentEnrollments: 0,
    isAds: true,
    level: "Advanced",
    modifiedAt: "2024-12-01",
  },
  {
    id: "AwOMY7WYNHFJvchiCwQS",
    modifiedAt: "2024-12-25",
    galleryImgs: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfkfFJWa_0VKg5NXQGdhHPIiylqBXfIL1tpA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    lessons: 40,
    description: "Master data analysis using R programming.",
    lecturerId: "RGVPhhghzLO6kIBBL0YPlNmOCli2",
    tags: ["R", "Data Analysis"],
    level: "Intermediate",
    title: "Data Science with R",
    featuredImage:
      "https://media.licdn.com/dms/image/v2/D5612AQFjCm3qGkwVog/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1694409110538?e=2147483647&v=beta&t=bkGt6-_RR-Z7S6UblDK2pWidK3902Qel8501nfPxhrM",
    createdAt: "2024-11-01",
    href: "/courses/data-science-r",
    category: "Data Science",
    price: 59.99,
    maxSeats: 20,
    currentEnrollments: 0,
    duration: "8 weeks",
    isAds: false,
  },
  {
    id: "P8IJTPll60DN4h7pWYpC",
    isAds: true,
    price: 34.99,
    category: "Marketing",
    lecturerId: "pPokxCtkWkR2x35Yh5GF72cDb2m2",
    level: "Beginner",
    createdAt: "2024-06-01",
    tags: ["Marketing", "Digital"],
    featuredImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv18v0cIWE-X9ng3LPnIaeGIGeTYLXTbd2FQ&s",
    maxSeats: 20,
    currentEnrollments: 0,
    lessons: 28,
    galleryImgs: [
      "https://nmfckzhfkmbyjwlmyfzd.supabase.co/storage/v1/object/public/lucas-cyber-academy/public/ZQ0KIYahqfQisPCmb6onUtAxS0D2/011495a9-2c7a-4e23-9bc8-8c623dd50d9b",
      "https://nmfckzhfkmbyjwlmyfzd.supabase.co/storage/v1/object/public/lucas-cyber-academy/public/ZQ0KIYahqfQisPCmb6onUtAxS0D2/1b82b388-d814-41b7-9569-a1f3921f4233",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    href: "/courses/digital-marketing",
    title: "Digital Marketing Essentials",
    duration: "6 weeks",
    description:
      "Boost your marketing skills with practical digital strategies.",
    modifiedAt: "2024-06-25",
  },
  {
    id: "SRDONdCJe3xuJpC9M6o2",
    href: "/courses/web-dev-bootcamp",
    isAds: true,
    category: "Web Development",
    price: 49.99,
    saleOff: "15%",
    maxSeats: 20,
    currentEnrollments: 0,
    modifiedAt: "2025-01-05",
    title: "Web Development Bootcamp",
    description: "Comprehensive course covering HTML, CSS, and JavaScript.",
    duration: "6 weeks",
    lecturerId: "pPokxCtkWkR2x35Yh5GF72cDb2m2",
    galleryImgs: [
      "https://blog.pwskills.com/wp-content/uploads/2023/05/Untitled-1-1.png",
      "https://miro.medium.com/v2/resize:fit:750/0*QmxDMtQShSHGzC6v.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    level: "Beginner",
    tags: ["HTML", "CSS", "JavaScript"],
    createdAt: "2024-12-15",
    lessons: 30,
    featuredImage:
      "https://blog.pwskills.com/wp-content/uploads/2023/05/Untitled-1-1.png",
  },
  {
    id: "YxT2xE08YXhqR8Ap8gQI",
    modifiedAt: "2024-04-15",
    level: "Intermediate",
    duration: "4 weeks",
    lessons: 22,
    price: 29.99,
    galleryImgs: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZbVVwmzsbW0k_BxaI57fOPuZeMGcBqY135w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Tt__mv0mtwLFb3ION7PR1aPMEHUZaB0wXg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    tags: ["Writing", "Creativity"],
    title: "Creative Writing Masterclass",
    description: "Enhance your storytelling and writing skills.",
    featuredImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZbVVwmzsbW0k_BxaI57fOPuZeMGcBqY135w&s",
    createdAt: "2024-04-01",
    category: "Writing",
    href: "/courses/creative-writing",
    maxSeats: 20,
    currentEnrollments: 0,
    isAds: true,
  },
  {
    id: "bJCHpd1kMuiNKp8Fj4ed",
    duration: "5 weeks",
    lessons: 25,
    level: "Beginner",
    featuredImage:
      "https://www.figma.com/community/resource/870fa7a3-4208-49c5-a85f-5fa824195087/thumbnail",
    href: "/courses/ui-ux-design",
    createdAt: "2024-09-01",
    modifiedAt: "2024-09-30",
    tags: ["UI", "UX", "Design"],
    galleryImgs: [
      "https://www.figma.com/community/resource/870fa7a3-4208-49c5-a85f-5fa824195087/thumbnail",
      "https://www.visily.ai/wp-content/uploads/2024/01/15-Fundamental-UX-Design-Principles-All-Designers-Should-Know.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    title: "UI/UX Design Principles",
    isAds: false,
    price: 39.99,
    description:
      "Learn the foundations of user interface and user experience design.",
    maxSeats: 20,
    currentEnrollments: 0,
    category: "Design",
  },
  {
    id: "h1TCXVNTAwerJmsydmKe",
    description: "Build predictive models using Python's powerful libraries.",
    lessons: 60,
    featuredImage:
      "https://cdn.activestate.com/wp-content/uploads/2020/02/Top10ML.png",
    createdAt: "2024-07-01",
    tags: ["Python", "Machine Learning", "AI"],
    galleryImgs: [
      "https://cdn.activestate.com/wp-content/uploads/2020/02/Top10ML.png",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnZzJ1F-ZTBzlHcC2BSqn_lSv3-pUH65B3RA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    modifiedAt: "2024-09-15",
    category: "Artificial Intelligence",
    level: "Intermediate",
    duration: "12 weeks",
    href: "/courses/machine-learning-python",
    price: 79.99,
    isAds: false,
    saleOff: "20%",
    maxSeats: 20,
    currentEnrollments: 0,
    title: "Machine Learning with Python",
  },
  {
    id: "hBMvLr4AKO9QM5reU5vX",
    isAds: true,
    level: "Beginner",
    tags: ["Security", "Cybersecurity"],
    modifiedAt: "2024-08-20",
    featuredImage:
      "https://digitalhealth.org.au/wp-content/uploads/2022/03/technology-security-concept-safety-digital-protection-system-1080x675.jpg",
    duration: "6 weeks",
    price: 44.99,
    href: "/courses/cybersecurity-basics",
    description:
      "Protect your systems and data with essential cybersecurity skills.",
    category: "IT & Security",
    galleryImgs: [
      "https://digitalhealth.org.au/wp-content/uploads/2022/03/technology-security-concept-safety-digital-protection-system-1080x675.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1k4i-DA6E-vn0tAIz1m-g0Zx2I2VdKubC1Q&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    createdAt: "2024-08-01",
    maxSeats: 20,
    currentEnrollments: 0,
    lessons: 35,
    title: "Cybersecurity Basics",
  },
  {
    id: "lL6w0YJqQqJAOKVq87je",
    duration: "4 weeks",
    title: "Introduction to Python",
    description: "Learn the basics of Python programming.",
    saleOff: "10%",
    lessons: 20,
    level: "Beginner",
    modifiedAt: "2025-01-10",
    featuredImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA58mH1EAjc2uEChw2pMg-Lkm9iUhR1U6Fbw&s",
    createdAt: "2025-01-01",
    price: 29.99,
    maxSeats: 20,
    currentEnrollments: 0,
    galleryImgs: [
      "https://i0.wp.com/junilearning.com/wp-content/uploads/2020/06/python-programming-language.webp?fit=1920%2C1920&ssl=1",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA58mH1EAjc2uEChw2pMg-Lkm9iUhR1U6Fbw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    tags: ["Python", "Programming", "Beginner"],
    href: "/courses/python-intro",
    category: "Programming",
    isAds: false,
  },
  {
    id: "nSbqgwVWIRQlmyWiqiVY",
    duration: "7 weeks",
    price: 49.99,
    description: "Understand the basics of cloud services and platforms.",
    saleOff: "10%",
    modifiedAt: "2024-05-20",
    featuredImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQL0J6y5wMaty33YPFLg_drIXd53AEiU7yfQ&s",
    galleryImgs: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQL0J6y5wMaty33YPFLg_drIXd53AEiU7yfQ&s",
      "https://media.licdn.com/dms/image/D4E12AQEOqinF9VYGsw/article-cover_image-shrink_720_1280/0/1701300069603?e=2147483647&v=beta&t=MOvpFEJwMa4YKkqBzq-p5APzEutI1Xx-ARnHvEiq1I8",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMSVfjpHHpdhQedd1zIrOsSv3UZJVmS_DUzg&s",
      "https://builtin.com/sites/www.builtin.com/files/2024-10/cybersecurity.png",
      "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    ],
    isAds: false,
    tags: ["Cloud", "AWS", "Azure"],
    category: "IT & Security",
    lessons: 33,
    level: "Beginner",
    createdAt: "2024-05-01",
    title: "Cloud Computing Fundamentals",
    maxSeats: 20,
    currentEnrollments: 0,
    href: "/courses/cloud-computing",
  },
];
